Repository OpenRVS-devs/OpenRVS, pull requests merged in 2020-05, with the labels that each got.

#24 Add locked to query from each server
  OpenRVS/classes/OpenClientBeaconReceiver.uc
  OpenRVS/classes/OpenMultiPlayerWidget.uc
Labels: enhancement, next release, not urgent

#27 Ping dev
  OpenRVS/classes/OpenMultiPlayerWidget.uc
  OpenRVS/classes/OpenTimer.uc
Labels: enhancement, next release

#31 Sorting refreshing
  OpenRVS/classes/OpenMultiPlayerWidget.uc
Labels: behind the scenes, bug, enhancement, next release, urgent

#32 Refactors OpenServerList for clarity
  OpenRVS/classes/OpenHTTPClient.uc
  OpenRVS/classes/OpenServerList.uc
  Servers.list
Labels: behind the scenes, next release

#39 Cleans up startup message logging
  OpenRVS/classes/OpenCustomMissionWidget.uc
  OpenRVS/classes/OpenMultiPlayerWidget.uc
  OpenRVS/classes/OpenServerList.uc
Labels: behind the scenes

#38 Fix issue - internet servers appearing in LAN tab
  OpenRVS/classes/OpenMultiPlayerWidget.uc
Labels: bug

#40 Adds basic version checking (log output) to the game
  OpenRVS/classes/OpenCustomMissionWidget.uc
  OpenRVS/classes/OpenHTTPClient.uc
  OpenRVS/classes/OpenRVS.uc
  OpenRVS/classes/OpenServer.uc
Labels: behind the scenes, enhancement, next release
